apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rhdp-rca.fullname" . }}-pvc
  labels:
    {{- include "rhdp-rca.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  storageClassName: {{ .Values.pvc.storageClassName }}
